export const cefinOfficeOptions = [
  { value: '국가청렴위원회', label: '국가청렴위원회' },
  { value: '국정홍보처', label: '국정홍보처' },
  { value: '대통령비서실', label: '대통령비서실' },
  { value: '식품의약품안전처', label: '식품의약품안전처' },
  { value: '통일부', label: '통일부' },
  { value: '경찰청', label: '경찰청' },
  { value: '기획재정부', label: '기획재정부' },
  { value: '중소벤처기업부', label: '중소벤처기업부' },
  { value: '국가인권위원회', label: '국가인권위원회' },
  { value: '교육부', label: '교육부' },
  { value: '중앙인사위원회', label: '중앙인사위원회' },
  { value: '관세청', label: '관세청' },
  { value: '문화체육관광부', label: '문화체육관광부' },
  { value: '건설교통부', label: '건설교통부' },
  { value: '행정안전부', label: '행정안전부' },
  { value: '외교부', label: '외교부' },
  { value: '농촌진흥청', label: '농촌진흥청' },
  { value: '산업자원부', label: '산업자원부' },
  { value: '문화관광부', label: '문화관광부' },
  { value: '지식경제부', label: '지식경제부' },
  { value: '소방청', label: '소방청' },
  { value: '4·16세월호참사 특별조사위원회', label: '4·16세월호참사 특별조사위원회' },
  { value: '국가청소년위원회', label: '국가청소년위원회' },
  { value: '국무조정실 및 국무총리비서실', label: '국무조정실 및 국무총리비서실' },
  { value: '새만금개발청', label: '새만금개발청' },
  { value: '국민경제자문회의', label: '국민경제자문회의' },
  { value: '대통령비서실 및 국가안보실', label: '대통령비서실 및 국가안보실' },
  { value: '보건복지부', label: '보건복지부' },
  { value: '국토해양부', label: '국토해양부' },
  { value: '산림청', label: '산림청' },
  { value: '진실·화해를위한과거사정리위원회', label: '진실·화해를위한과거사정리위원회' },
  { value: '과학기술부', label: '과학기술부' },
  { value: '국세청', label: '국세청' },
  { value: '농림부', label: '농림부' },
  { value: '환경부', label: '환경부' },
  { value: '재정경제부', label: '재정경제부' },
  { value: '과학기술정보통신부', label: '과학기술정보통신부' },
  { value: '해양수산부', label: '해양수산부' },
  { value: '정보통신부', label: '정보통신부' },
  { value: '중앙선거관리위원회', label: '중앙선거관리위원회' },
  { value: '대법원', label: '대법원' },
  { value: '고위공직자범죄수사처', label: '고위공직자범죄수사처' },
  { value: '교육과학기술부', label: '교육과학기술부' },
  { value: '문화재청', label: '문화재청' },
  { value: '특임장관실', label: '특임장관실' },
  { value: '질병관리청', label: '질병관리청' },
  { value: '법제처', label: '법제처' },
  { value: '특허청', label: '특허청' },
  { value: '고용노동부', label: '고용노동부' },
  { value: '감사원', label: '감사원' },
  { value: '산업통상자원부', label: '산업통상자원부' },
  { value: '방송통신위원회', label: '방송통신위원회' },
  { value: '여성가족부', label: '여성가족부' },
  { value: '대통령경호실', label: '대통령경호실' },
  { value: '원자력안전위원회', label: '원자력안전위원회' },
  { value: '법무부', label: '법무부' },
  { value: '기획예산처', label: '기획예산처' },
  { value: '통계청', label: '통계청' },
  { value: '해양경찰청', label: '해양경찰청' },
  { value: '국방부', label: '국방부' },
  { value: '중소기업청', label: '중소기업청' },
  {
    value: '가습기살균제사건과 4·16세월호참사 특별조사위원회',
    label: '가습기살균제사건과 4·16세월호참사 특별조사위원회',
  },
  { value: '교육인적자원부', label: '교육인적자원부' },
  { value: '5·18민주화운동 진상규명조사위원회', label: '5·18민주화운동 진상규명조사위원회' },
  { value: '친일반민족행위진상규명위원회', label: '친일반민족행위진상규명위원회' },
  { value: '식품의약품안전청', label: '식품의약품안전청' },
  { value: '국무총리실', label: '국무총리실' },
  { value: '안전행정부', label: '안전행정부' },
  { value: '금융위원회', label: '금융위원회' },
  { value: '국가과학기술위원회', label: '국가과학기술위원회' },
  { value: '국토교통부', label: '국토교통부' },
  { value: '외교통상부', label: '외교통상부' },
  { value: '공정거래위원회', label: '공정거래위원회' },
  { value: '농림축산식품부', label: '농림축산식품부' },
  { value: '방위사업청', label: '방위사업청' },
  { value: '국민권익위원회', label: '국민권익위원회' },
  { value: '민주평화통일자문회의', label: '민주평화통일자문회의' },
  { value: '대통령실', label: '대통령실' },
  { value: '개인정보보호위원회', label: '개인정보보호위원회' },
  { value: '보건복지가족부', label: '보건복지가족부' },
  { value: '국가안전보장회의', label: '국가안전보장회의' },
  { value: '노동부', label: '노동부' },
  { value: '조달청', label: '조달청' },
  { value: '농림수산식품부', label: '농림수산식품부' },
  { value: '미래창조과학부', label: '미래창조과학부' },
  { value: '방송위원회', label: '방송위원회' },
  { value: '소방방재청', label: '소방방재청' },
  { value: '행정중심복합도시건설청', label: '행정중심복합도시건설청' },
  { value: '국민안전처', label: '국민안전처' },
  { value: '국민고충처리위원회', label: '국민고충처리위원회' },
  { value: '병무청', label: '병무청' },
  { value: '대통령경호처', label: '대통령경호처' },
  { value: '인사혁신처', label: '인사혁신처' },
  { value: '여성부', label: '여성부' },
  { value: '행정자치부', label: '행정자치부' },
  { value: '국가정보원', label: '국가정보원' },
  { value: '국회', label: '국회' },
  { value: '기상청', label: '기상청' },
  { value: '국가보훈처', label: '국가보훈처' },
  { value: '헌법재판소', label: '헌법재판소' },
] as const

export const cefinOfficeDefaultOption = cefinOfficeOptions[0]

export function getCefinOfficeOption(value: string) {
  return cefinOfficeOptions.find((l) => l.value === value)
}

export const cefinFieldOptions = [
  { value: '교육', label: '교육' },
  { value: '국방', label: '국방' },
  { value: '보건', label: '보건' },
  { value: '통신', label: '통신' },
  { value: '환경', label: '환경' },
  { value: '외교·통일', label: '외교·통일' },
  { value: '통일·외교', label: '통일·외교' },
  { value: '산업·중소기업', label: '산업·중소기업' },
  { value: '일반·지방행정', label: '일반·지방행정' },
  { value: '산업·중소기업및에너지', label: '산업·중소기업및에너지' },
  { value: '예비비', label: '예비비' },
  { value: '과학기술', label: '과학기술' },
  { value: '농림수산', label: '농림수산' },
  { value: '사회복지', label: '사회복지' },
  { value: '지역개발', label: '지역개발' },
  { value: '환경보호', label: '환경보호' },
  { value: '교통및물류', label: '교통및물류' },
  { value: '문화및관광', label: '문화및관광' },
  { value: '수송및교통', label: '수송및교통' },
  { value: '농림해양수산', label: '농림해양수산' },
  { value: '일반공공행정', label: '일반공공행정' },
  { value: '공공질서및안전', label: '공공질서및안전' },
  { value: '국토및지역개발', label: '국토및지역개발' },
] as const

export const cefinFieldDefaultOption = cefinFieldOptions[13]

export function getCefinFieldOption(value: string) {
  return cefinFieldOptions.find((l) => l.value === value)
}

export const cefinSectorOptions = [
  { value: '경찰', label: '경찰' },
  { value: '고용', label: '고용' },
  { value: '관광', label: '관광' },
  { value: '노동', label: '노동' },
  { value: '노인', label: '노인' },
  { value: '대기', label: '대기' },
  { value: '도로', label: '도로' },
  { value: '보훈', label: '보훈' },
  { value: '우정', label: '우정' },
  { value: '자연', label: '자연' },
  { value: '주택', label: '주택' },
  { value: '철도', label: '철도' },
  { value: '체육', label: '체육' },
  { value: '통일', label: '통일' },
  { value: '해경', label: '해경' },
  { value: '해양', label: '해양' },
  { value: '농업·농촌', label: '농업·농촌' },
  { value: '수산·어촌', label: '수산·어촌' },
  { value: '아동·보육', label: '아동·보육' },
  { value: '외교·통상', label: '외교·통상' },
  { value: '임업·산촌', label: '임업·산촌' },
  { value: '재정·금융', label: '재정·금융' },
  { value: '항공·공항', label: '항공·공항' },
  { value: '해운·항만', label: '해운·항만' },
  { value: '여성·가족·청소년', label: '여성·가족·청소년' },
  { value: '노인·청소년', label: '노인·청소년' },
  { value: '평생·직업교육', label: '평생·직업교육' },
  { value: '보육·가족및여성', label: '보육·가족및여성' },
  { value: '산업·중소기업일반', label: '산업·중소기업일반' },
  { value: '문화재', label: '문화재' },
  { value: '물환경', label: '물환경' },
  { value: '수자원', label: '수자원' },
  { value: '식품업', label: '식품업' },
  { value: '예비비', label: '예비비' },
  { value: '폐기물', label: '폐기물' },
  { value: '건강보험', label: '건강보험' },
  { value: '고등교육', label: '고등교육' },
  { value: '공적연금', label: '공적연금' },
  { value: '교육일반', label: '교육일반' },
  { value: '국정운영', label: '국정운영' },
  { value: '기술개발', label: '기술개발' },
  { value: '도시철도', label: '도시철도' },
  { value: '문화예술', label: '문화예술' },
  { value: '방송통신', label: '방송통신' },
  { value: '병력운영', label: '병력운영' },
  { value: '병무행정', label: '병무행정' },
  { value: '보건의료', label: '보건의료' },
  { value: '산업단지', label: '산업단지' },
  { value: '일반행정', label: '일반행정' },
  { value: '자연환경', label: '자연환경' },
  { value: '재난관리', label: '재난관리' },
  { value: '전력유지', label: '전력유지' },
  { value: '정보통신', label: '정보통신' },
  { value: '해양환경', label: '해양환경' },
  { value: '환경일반', label: '환경일반' },
  { value: '상하수도·수질', label: '상하수도·수질' },
  { value: '해양수산·어촌', label: '해양수산·어촌' },
  { value: '산업진흥·고도화', label: '산업진흥·고도화' },
  { value: '재난방재·민방위', label: '재난방재·민방위' },
  { value: '지방행정·재정지원', label: '지방행정·재정지원' },
  { value: '물류등기타', label: '물류등기타' },
  { value: '방위력개선', label: '방위력개선' },
  { value: '법무및검찰', label: '법무및검찰' },
  { value: '법원및헌재', label: '법원및헌재' },
  { value: '지역및도시', label: '지역및도시' },
  { value: '창업및벤처', label: '창업및벤처' },
  { value: '고용노동일반', label: '고용노동일반' },
  { value: '과학기술일반', label: '과학기술일반' },
  { value: '기초생활보장', label: '기초생활보장' },
  { value: '사회복지일반', label: '사회복지일반' },
  { value: '산업금융지원', label: '산업금융지원' },
  { value: '산업기술지원', label: '산업기술지원' },
  { value: '산업혁신지원', label: '산업혁신지원' },
  { value: '식품의약안전', label: '식품의약안전' },
  { value: '정부자원관리', label: '정부자원관리' },
  { value: '지식재산일반', label: '지식재산일반' },
  { value: '취약계층지원', label: '취약계층지원' },
  { value: '환경보호일반', label: '환경보호일반' },
  { value: '무역및투자유치', label: '무역및투자유치' },
  { value: '문화및관광일반', label: '문화및관광일반' },
  { value: '입법및선거관리', label: '입법및선거관리' },
  { value: '과학기술연구개발', label: '과학기술연구개발' },
  { value: '과학기술연구지원', label: '과학기술연구지원' },
  { value: '에너지및자원개발', label: '에너지및자원개발' },
  { value: '유아및초중등교육', label: '유아및초중등교육' },
  { value: '과학기술인력및문화', label: '과학기술인력및문화' },
  { value: '기후대기및환경안전', label: '기후대기및환경안전' },
  { value: '자원순환및환경경제', label: '자원순환및환경경제' },
  { value: '중소기업및소상공인육성', label: '중소기업및소상공인육성' },
] as const

export const cefinSectorDefaultOption = cefinSectorOptions[68]

export function getCefinSectorOption(value: string) {
  return cefinSectorOptions.find((l) => l.value === value)
}
