export const centerOfficeOptions = [
  { value: '국가청렴위원회', label: '국가청렴위원회' },
  { value: '국정홍보처', label: '국정홍보처' },
  { value: '대통령비서실', label: '대통령비서실' },
  { value: '식품의약품안전처', label: '식품의약품안전처' },
  { value: '통일부', label: '통일부' },
  { value: '경찰청', label: '경찰청' },
  { value: '기획재정부', label: '기획재정부' },
  { value: '중소벤처기업부', label: '중소벤처기업부' },
  { value: '국가인권위원회', label: '국가인권위원회' },
  { value: '교육부', label: '교육부' },
  { value: '중앙인사위원회', label: '중앙인사위원회' },
  { value: '관세청', label: '관세청' },
  { value: '문화체육관광부', label: '문화체육관광부' },
  { value: '건설교통부', label: '건설교통부' },
  { value: '행정안전부', label: '행정안전부' },
  { value: '외교부', label: '외교부' },
  { value: '농촌진흥청', label: '농촌진흥청' },
  { value: '산업자원부', label: '산업자원부' },
  { value: '문화관광부', label: '문화관광부' },
  { value: '지식경제부', label: '지식경제부' },
  { value: '소방청', label: '소방청' },
  { value: '4·16세월호참사 특별조사위원회', label: '4·16세월호참사 특별조사위원회' },
  { value: '국가청소년위원회', label: '국가청소년위원회' },
  { value: '국무조정실 및 국무총리비서실', label: '국무조정실 및 국무총리비서실' },
  { value: '새만금개발청', label: '새만금개발청' },
  { value: '국민경제자문회의', label: '국민경제자문회의' },
  { value: '대통령비서실 및 국가안보실', label: '대통령비서실 및 국가안보실' },
  { value: '보건복지부', label: '보건복지부' },
  { value: '국토해양부', label: '국토해양부' },
  { value: '산림청', label: '산림청' },
  { value: '진실·화해를위한과거사정리위원회', label: '진실·화해를위한과거사정리위원회' },
  { value: '과학기술부', label: '과학기술부' },
  { value: '국세청', label: '국세청' },
  { value: '농림부', label: '농림부' },
  { value: '환경부', label: '환경부' },
  { value: '재정경제부', label: '재정경제부' },
  { value: '과학기술정보통신부', label: '과학기술정보통신부' },
  { value: '해양수산부', label: '해양수산부' },
  { value: '정보통신부', label: '정보통신부' },
  { value: '중앙선거관리위원회', label: '중앙선거관리위원회' },
  { value: '대법원', label: '대법원' },
  { value: '고위공직자범죄수사처', label: '고위공직자범죄수사처' },
  { value: '교육과학기술부', label: '교육과학기술부' },
  { value: '문화재청', label: '문화재청' },
  { value: '특임장관실', label: '특임장관실' },
  { value: '질병관리청', label: '질병관리청' },
  { value: '법제처', label: '법제처' },
  { value: '특허청', label: '특허청' },
  { value: '고용노동부', label: '고용노동부' },
  { value: '감사원', label: '감사원' },
  { value: '산업통상자원부', label: '산업통상자원부' },
  { value: '방송통신위원회', label: '방송통신위원회' },
  { value: '여성가족부', label: '여성가족부' },
  { value: '대통령경호실', label: '대통령경호실' },
  { value: '원자력안전위원회', label: '원자력안전위원회' },
  { value: '법무부', label: '법무부' },
  { value: '기획예산처', label: '기획예산처' },
  { value: '통계청', label: '통계청' },
  { value: '해양경찰청', label: '해양경찰청' },
  { value: '국방부', label: '국방부' },
  { value: '중소기업청', label: '중소기업청' },
  {
    value: '가습기살균제사건과 4·16세월호참사 특별조사위원회',
    label: '가습기살균제사건과 4·16세월호참사 특별조사위원회',
  },
  { value: '교육인적자원부', label: '교육인적자원부' },
  { value: '5·18민주화운동 진상규명조사위원회', label: '5·18민주화운동 진상규명조사위원회' },
  { value: '친일반민족행위진상규명위원회', label: '친일반민족행위진상규명위원회' },
  { value: '식품의약품안전청', label: '식품의약품안전청' },
  { value: '국무총리실', label: '국무총리실' },
  { value: '안전행정부', label: '안전행정부' },
  { value: '금융위원회', label: '금융위원회' },
  { value: '국가과학기술위원회', label: '국가과학기술위원회' },
  { value: '국토교통부', label: '국토교통부' },
  { value: '외교통상부', label: '외교통상부' },
  { value: '공정거래위원회', label: '공정거래위원회' },
  { value: '농림축산식품부', label: '농림축산식품부' },
  { value: '방위사업청', label: '방위사업청' },
  { value: '국민권익위원회', label: '국민권익위원회' },
  { value: '민주평화통일자문회의', label: '민주평화통일자문회의' },
  { value: '대통령실', label: '대통령실' },
  { value: '개인정보보호위원회', label: '개인정보보호위원회' },
  { value: '보건복지가족부', label: '보건복지가족부' },
  { value: '국가안전보장회의', label: '국가안전보장회의' },
  { value: '노동부', label: '노동부' },
  { value: '조달청', label: '조달청' },
  { value: '농림수산식품부', label: '농림수산식품부' },
  { value: '미래창조과학부', label: '미래창조과학부' },
  { value: '방송위원회', label: '방송위원회' },
  { value: '소방방재청', label: '소방방재청' },
  { value: '행정중심복합도시건설청', label: '행정중심복합도시건설청' },
  { value: '국민안전처', label: '국민안전처' },
  { value: '국민고충처리위원회', label: '국민고충처리위원회' },
  { value: '병무청', label: '병무청' },
  { value: '대통령경호처', label: '대통령경호처' },
  { value: '인사혁신처', label: '인사혁신처' },
  { value: '여성부', label: '여성부' },
  { value: '행정자치부', label: '행정자치부' },
  { value: '국가정보원', label: '국가정보원' },
  { value: '국회', label: '국회' },
  { value: '기상청', label: '기상청' },
  { value: '국가보훈처', label: '국가보훈처' },
  { value: '헌법재판소', label: '헌법재판소' },
]
