export const voteOptions = [
  {
    label: '강원도',
    options: [
      { group: '강원도', value: '강원도', label: '전체' },
      { group: '강원도', value: '강릉시', label: '강릉시' },
      { group: '강원도', value: '고성군', label: '고성군' },
      { group: '강원도', value: '동해시', label: '동해시' },
      { group: '강원도', value: '삼척시', label: '삼척시' },
      { group: '강원도', value: '속초시', label: '속초시' },
      { group: '강원도', value: '양구군', label: '양구군' },
      { group: '강원도', value: '양양군', label: '양양군' },
      { group: '강원도', value: '원주시', label: '원주시' },
      { group: '강원도', value: '인제군', label: '인제군' },
      { group: '강원도', value: '정선군', label: '정선군' },
      { group: '강원도', value: '철원군', label: '철원군' },
      { group: '강원도', value: '춘천시', label: '춘천시' },
      { group: '강원도', value: '태백시', label: '태백시' },
      { group: '강원도', value: '평창군', label: '평창군' },
      { group: '강원도', value: '홍천군', label: '홍천군' },
      { group: '강원도', value: '화천군', label: '화천군' },
      { group: '강원도', value: '횡성군', label: '횡성군' },
    ],
  },
  {
    label: '경기도',
    options: [
      { group: '경기도', value: '경기도', label: '전체' },
      { group: '경기도', value: '가평군', label: '가평군' },
      { group: '경기도', value: '고양시', label: '고양시' },
      { group: '경기도', value: '과천시', label: '과천시' },
      { group: '경기도', value: '광명시', label: '광명시' },
      { group: '경기도', value: '광주시', label: '광주시' },
      { group: '경기도', value: '구리시', label: '구리시' },
      { group: '경기도', value: '군포시', label: '군포시' },
      { group: '경기도', value: '김포시', label: '김포시' },
      { group: '경기도', value: '남양주시', label: '남양주시' },
      { group: '경기도', value: '동두천시', label: '동두천시' },
      { group: '경기도', value: '부천시', label: '부천시' },
      { group: '경기도', value: '성남시', label: '성남시' },
      { group: '경기도', value: '수원시', label: '수원시' },
      { group: '경기도', value: '시흥시', label: '시흥시' },
      { group: '경기도', value: '안산시', label: '안산시' },
      { group: '경기도', value: '안성시', label: '안성시' },
      { group: '경기도', value: '안양시', label: '안양시' },
      { group: '경기도', value: '양주시', label: '양주시' },
      { group: '경기도', value: '양평군', label: '양평군' },
      { group: '경기도', value: '여주시', label: '여주시' },
      { group: '경기도', value: '연천군', label: '연천군' },
      { group: '경기도', value: '오산시', label: '오산시' },
      { group: '경기도', value: '용인시', label: '용인시' },
      { group: '경기도', value: '의정부시', label: '의정부시' },
      { group: '경기도', value: '이천시', label: '이천시' },
      { group: '경기도', value: '평택시', label: '평택시' },
      { group: '경기도', value: '포천시', label: '포천시' },
      { group: '경기도', value: '하남시', label: '하남시' },
      { group: '경기도', value: '화성시', label: '화성시' },
    ],
  },
  {
    label: '경상남도',
    options: [
      { group: '경상남도', value: '경상남도', label: '전체' },
      { group: '경상남도', value: '거창군', label: '거창군' },
      { group: '경상남도', value: '고성군', label: '고성군' },
      { group: '경상남도', value: '김해시', label: '김해시' },
      { group: '경상남도', value: '남해군', label: '남해군' },
      { group: '경상남도', value: '사천시', label: '사천시' },
      { group: '경상남도', value: '산청군', label: '산청군' },
      { group: '경상남도', value: '양산시', label: '양산시' },
      { group: '경상남도', value: '의령군', label: '의령군' },
      { group: '경상남도', value: '진주시', label: '진주시' },
      { group: '경상남도', value: '창녕군', label: '창녕군' },
      { group: '경상남도', value: '창원시', label: '창원시' },
      { group: '경상남도', value: '통영시', label: '통영시' },
      { group: '경상남도', value: '하동군', label: '하동군' },
      { group: '경상남도', value: '함안군', label: '함안군' },
      { group: '경상남도', value: '함양군', label: '함양군' },
      { group: '경상남도', value: '합천군', label: '합천군' },
    ],
  },
  {
    label: '경상북도',
    options: [
      { group: '경상북도', value: '경상북도', label: '전체' },
      { group: '경상북도', value: '경산시', label: '경산시' },
      { group: '경상북도', value: '군위군', label: '군위군' },
      { group: '경상북도', value: '김천시', label: '김천시' },
      { group: '경상북도', value: '문경시', label: '문경시' },
      { group: '경상북도', value: '봉화군', label: '봉화군' },
      { group: '경상북도', value: '상주시', label: '상주시' },
      { group: '경상북도', value: '영덕군', label: '영덕군' },
      { group: '경상북도', value: '영양군', label: '영양군' },
      { group: '경상북도', value: '영주시', label: '영주시' },
      { group: '경상북도', value: '영천시', label: '영천시' },
      { group: '경상북도', value: '예천군', label: '예천군' },
      { group: '경상북도', value: '울릉군', label: '울릉군' },
      { group: '경상북도', value: '울진군', label: '울진군' },
      { group: '경상북도', value: '의성군', label: '의성군' },
      { group: '경상북도', value: '청송군', label: '청송군' },
      { group: '경상북도', value: '칠곡군', label: '칠곡군' },
    ],
  },
  {
    label: '광주광역시',
    options: [
      { group: '광주광역시', value: '광주광역시', label: '전체' },
      { group: '광주광역시', value: '광산구', label: '광산구' },
      { group: '광주광역시', value: '남구', label: '남구' },
      { group: '광주광역시', value: '동구', label: '동구' },
      { group: '광주광역시', value: '북구', label: '북구' },
      { group: '광주광역시', value: '서구', label: '서구' },
    ],
  },
  {
    label: '대구광역시',
    options: [
      { group: '대구광역시', value: '대구광역시', label: '전체' },
      { group: '대구광역시', value: '남구', label: '남구' },
      { group: '대구광역시', value: '달서구', label: '달서구' },
      { group: '대구광역시', value: '달성군', label: '달성군' },
      { group: '대구광역시', value: '동구', label: '동구' },
      { group: '대구광역시', value: '북구', label: '북구' },
      { group: '대구광역시', value: '서구', label: '서구' },
      { group: '대구광역시', value: '수성구', label: '수성구' },
      { group: '대구광역시', value: '중구', label: '중구' },
    ],
  },
  {
    label: '대전광역시',
    options: [
      { group: '대전광역시', value: '대전광역시', label: '전체' },
      { group: '대전광역시', value: '대덕구', label: '대덕구' },
      { group: '대전광역시', value: '동구', label: '동구' },
      { group: '대전광역시', value: '서구', label: '서구' },
      { group: '대전광역시', value: '유성구', label: '유성구' },
      { group: '대전광역시', value: '중구', label: '중구' },
    ],
  },
  {
    label: '부산광역시',
    options: [
      { group: '부산광역시', value: '부산광역시', label: '전체' },
      { group: '부산광역시', value: '강서구', label: '강서구' },
      { group: '부산광역시', value: '금정구', label: '금정구' },
      { group: '부산광역시', value: '기장군', label: '기장군' },
      { group: '부산광역시', value: '남구', label: '남구' },
      { group: '부산광역시', value: '동구', label: '동구' },
      { group: '부산광역시', value: '동래구', label: '동래구' },
      { group: '부산광역시', value: '부산진구', label: '부산진구' },
      { group: '부산광역시', value: '북구', label: '북구' },
      { group: '부산광역시', value: '사상구', label: '사상구' },
      { group: '부산광역시', value: '사하구', label: '사하구' },
      { group: '부산광역시', value: '서구', label: '서구' },
      { group: '부산광역시', value: '수영구', label: '수영구' },
      { group: '부산광역시', value: '연제구', label: '연제구' },
      { group: '부산광역시', value: '영도구', label: '영도구' },
      { group: '부산광역시', value: '중구', label: '중구' },
      { group: '부산광역시', value: '해운대구', label: '해운대구' },
    ],
  },
  {
    label: '서울특별시',
    options: [
      { group: '서울특별시', value: '서울특별시', label: '전체' },
      { group: '서울특별시', value: '강남구', label: '강남구' },
      { group: '서울특별시', value: '강동구', label: '강동구' },
      { group: '서울특별시', value: '강북구', label: '강북구' },
      { group: '서울특별시', value: '강서구', label: '강서구' },
      { group: '서울특별시', value: '관악구', label: '관악구' },
      { group: '서울특별시', value: '광진구', label: '광진구' },
      { group: '서울특별시', value: '구로구', label: '구로구' },
      { group: '서울특별시', value: '금천구', label: '금천구' },
      { group: '서울특별시', value: '노원구', label: '노원구' },
      { group: '서울특별시', value: '도봉구', label: '도봉구' },
      { group: '서울특별시', value: '동대문구', label: '동대문구' },
      { group: '서울특별시', value: '동작구', label: '동작구' },
      { group: '서울특별시', value: '마포구', label: '마포구' },
      { group: '서울특별시', value: '서대문구', label: '서대문구' },
      { group: '서울특별시', value: '서초구', label: '서초구' },
      { group: '서울특별시', value: '성동구', label: '성동구' },
      { group: '서울특별시', value: '성북구', label: '성북구' },
      { group: '서울특별시', value: '송파구', label: '송파구' },
      { group: '서울특별시', value: '양천구', label: '양천구' },
      { group: '서울특별시', value: '영등포구', label: '영등포구' },
      { group: '서울특별시', value: '용산구', label: '용산구' },
      { group: '서울특별시', value: '은평구', label: '은평구' },
      { group: '서울특별시', value: '종로구', label: '종로구' },
      { group: '서울특별시', value: '중구', label: '중구' },
      { group: '서울특별시', value: '중랑구', label: '중랑구' },
    ],
  },
  {
    label: '세종특별자치시',
    options: [{ group: '세종특별자치시', value: '세종특별자치시', label: '전체' }],
  },
  {
    label: '울산광역시',
    options: [
      { group: '울산광역시', value: '울산광역시', label: '전체' },
      { group: '울산광역시', value: '남구', label: '남구' },
      { group: '울산광역시', value: '동구', label: '동구' },
      { group: '울산광역시', value: '북구', label: '북구' },
      { group: '울산광역시', value: '울주군', label: '울주군' },
      { group: '울산광역시', value: '중구', label: '중구' },
    ],
  },
  {
    label: '인천광역시',
    options: [
      { group: '인천광역시', value: '인천광역시', label: '전체' },
      { group: '인천광역시', value: '강화군', label: '강화군' },
      { group: '인천광역시', value: '계양구', label: '계양구' },
      { group: '인천광역시', value: '남동구', label: '남동구' },
      { group: '인천광역시', value: '부평구', label: '부평구' },
      { group: '인천광역시', value: '서구', label: '서구' },
      { group: '인천광역시', value: '연수구', label: '연수구' },
      { group: '인천광역시', value: '옹진군', label: '옹진군' },
      { group: '인천광역시', value: '중구', label: '중구' },
    ],
  },
  {
    label: '전국',
    options: [{ group: '전국', value: '대한민국', label: '대한민국' }],
  },
  {
    label: '전라남도',
    options: [
      { group: '전라남도', value: '전라남도', label: '전체' },
      { group: '전라남도', value: '강진군', label: '강진군' },
      { group: '전라남도', value: '곡성군', label: '곡성군' },
      { group: '전라남도', value: '광양시', label: '광양시' },
      { group: '전라남도', value: '무안군', label: '무안군' },
      { group: '전라남도', value: '보성군', label: '보성군' },
      { group: '전라남도', value: '순천시', label: '순천시' },
      { group: '전라남도', value: '영광군', label: '영광군' },
      { group: '전라남도', value: '영암군', label: '영암군' },
      { group: '전라남도', value: '완도군', label: '완도군' },
      { group: '전라남도', value: '장성군', label: '장성군' },
      { group: '전라남도', value: '장흥군', label: '장흥군' },
      { group: '전라남도', value: '함평군', label: '함평군' },
      { group: '전라남도', value: '해남군', label: '해남군' },
      { group: '전라남도', value: '화순군', label: '화순군' },
    ],
  },
  {
    label: '전라북도',
    options: [
      { group: '전라북도', value: '전라북도', label: '전체' },
      { group: '전라북도', value: '고창군', label: '고창군' },
      { group: '전라북도', value: '군산시', label: '군산시' },
      { group: '전라북도', value: '무주군', label: '무주군' },
      { group: '전라북도', value: '완주군', label: '완주군' },
      { group: '전라북도', value: '임실군', label: '임실군' },
      { group: '전라북도', value: '정읍시', label: '정읍시' },
      { group: '전라북도', value: '진안군', label: '진안군' },
    ],
  },
  {
    label: '제주특별자치도',
    options: [{ group: '제주특별자치도', value: '제주특별자치도', label: '전체' }],
  },
  {
    label: '충청남도',
    options: [
      { group: '충청남도', value: '충청남도', label: '전체' },
      { group: '충청남도', value: '계룡시', label: '계룡시' },
      { group: '충청남도', value: '금산군', label: '금산군' },
      { group: '충청남도', value: '보령시', label: '보령시' },
      { group: '충청남도', value: '부여군', label: '부여군' },
      { group: '충청남도', value: '서천군', label: '서천군' },
      { group: '충청남도', value: '아산시', label: '아산시' },
      { group: '충청남도', value: '예산군', label: '예산군' },
      { group: '충청남도', value: '천안시', label: '천안시' },
    ],
  },
  {
    label: '충청북도',
    options: [
      { group: '충청북도', value: '충청북도', label: '전체' },
      { group: '충청북도', value: '보은군', label: '보은군' },
      { group: '충청북도', value: '옥천군', label: '옥천군' },
      { group: '충청북도', value: '제천시', label: '제천시' },
      { group: '충청북도', value: '청주시', label: '청주시' },
      { group: '충청북도', value: '충주시', label: '충주시' },
    ],
  },
]
